// Code generated by ent, DO NOT EDIT.

package execution

import (
	"encoding/json"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the execution type in the database.
	Label = "execution"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCurrentNode holds the string denoting the current_node field in the database.
	FieldCurrentNode = "current_node"
	// FieldVariables holds the string denoting the variables field in the database.
	FieldVariables = "variables"
	// FieldMessages holds the string denoting the messages field in the database.
	FieldMessages = "messages"
	// FieldNodeResults holds the string denoting the node_results field in the database.
	FieldNodeResults = "node_results"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeGraph holds the string denoting the graph edge name in mutations.
	EdgeGraph = "graph"
	// Table holds the table name of the execution in the database.
	Table = "executions"
	// GraphTable is the table that holds the graph relation/edge.
	GraphTable = "executions"
	// GraphInverseTable is the table name for the Graph entity.
	// It exists in this package in order to avoid circular dependency with the "graph" package.
	GraphInverseTable = "graphs"
	// GraphColumn is the table column denoting the graph relation/edge.
	GraphColumn = "graph_executions"
)

// Columns holds all SQL columns for execution fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldCurrentNode,
	FieldVariables,
	FieldMessages,
	FieldNodeResults,
	FieldError,
	FieldStartedAt,
	FieldCompletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "executions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"graph_executions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// CurrentNodeValidator is a validator for the "current_node" field. It is called by the builders before save.
	CurrentNodeValidator func(string) error
	// DefaultVariables holds the default value on creation for the "variables" field.
	DefaultVariables json.RawMessage
	// DefaultMessages holds the default value on creation for the "messages" field.
	DefaultMessages json.RawMessage
	// DefaultNodeResults holds the default value on creation for the "node_results" field.
	DefaultNodeResults json.RawMessage
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending     Status = "pending"
	StatusRunning     Status = "running"
	StatusCompleted   Status = "completed"
	StatusFailed      Status = "failed"
	StatusCancelled   Status = "cancelled"
	StatusInterrupted Status = "interrupted"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusRunning, StatusCompleted, StatusFailed, StatusCancelled, StatusInterrupted:
		return nil
	default:
		return fmt.Errorf("execution: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Execution queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCurrentNode orders the results by the current_node field.
func ByCurrentNode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentNode, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGraphField orders the results by graph field.
func ByGraphField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGraphStep(), sql.OrderByField(field, opts...))
	}
}
func newGraphStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GraphInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GraphTable, GraphColumn),
	)
}
