// Code generated by ent, DO NOT EDIT.

package execution

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/aescanero/dago/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Execution {
	return predicate.Execution(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Execution {
	return predicate.Execution(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Execution {
	return predicate.Execution(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Execution {
	return predicate.Execution(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Execution {
	return predicate.Execution(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Execution {
	return predicate.Execution(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Execution {
	return predicate.Execution(sql.FieldLTE(FieldID, id))
}

// CurrentNode applies equality check predicate on the "current_node" field. It's identical to CurrentNodeEQ.
func CurrentNode(v string) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldCurrentNode, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldError, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Execution {
	return predicate.Execution(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Execution {
	return predicate.Execution(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Execution {
	return predicate.Execution(sql.FieldNotIn(FieldStatus, vs...))
}

// CurrentNodeEQ applies the EQ predicate on the "current_node" field.
func CurrentNodeEQ(v string) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldCurrentNode, v))
}

// CurrentNodeNEQ applies the NEQ predicate on the "current_node" field.
func CurrentNodeNEQ(v string) predicate.Execution {
	return predicate.Execution(sql.FieldNEQ(FieldCurrentNode, v))
}

// CurrentNodeIn applies the In predicate on the "current_node" field.
func CurrentNodeIn(vs ...string) predicate.Execution {
	return predicate.Execution(sql.FieldIn(FieldCurrentNode, vs...))
}

// CurrentNodeNotIn applies the NotIn predicate on the "current_node" field.
func CurrentNodeNotIn(vs ...string) predicate.Execution {
	return predicate.Execution(sql.FieldNotIn(FieldCurrentNode, vs...))
}

// CurrentNodeGT applies the GT predicate on the "current_node" field.
func CurrentNodeGT(v string) predicate.Execution {
	return predicate.Execution(sql.FieldGT(FieldCurrentNode, v))
}

// CurrentNodeGTE applies the GTE predicate on the "current_node" field.
func CurrentNodeGTE(v string) predicate.Execution {
	return predicate.Execution(sql.FieldGTE(FieldCurrentNode, v))
}

// CurrentNodeLT applies the LT predicate on the "current_node" field.
func CurrentNodeLT(v string) predicate.Execution {
	return predicate.Execution(sql.FieldLT(FieldCurrentNode, v))
}

// CurrentNodeLTE applies the LTE predicate on the "current_node" field.
func CurrentNodeLTE(v string) predicate.Execution {
	return predicate.Execution(sql.FieldLTE(FieldCurrentNode, v))
}

// CurrentNodeContains applies the Contains predicate on the "current_node" field.
func CurrentNodeContains(v string) predicate.Execution {
	return predicate.Execution(sql.FieldContains(FieldCurrentNode, v))
}

// CurrentNodeHasPrefix applies the HasPrefix predicate on the "current_node" field.
func CurrentNodeHasPrefix(v string) predicate.Execution {
	return predicate.Execution(sql.FieldHasPrefix(FieldCurrentNode, v))
}

// CurrentNodeHasSuffix applies the HasSuffix predicate on the "current_node" field.
func CurrentNodeHasSuffix(v string) predicate.Execution {
	return predicate.Execution(sql.FieldHasSuffix(FieldCurrentNode, v))
}

// CurrentNodeIsNil applies the IsNil predicate on the "current_node" field.
func CurrentNodeIsNil() predicate.Execution {
	return predicate.Execution(sql.FieldIsNull(FieldCurrentNode))
}

// CurrentNodeNotNil applies the NotNil predicate on the "current_node" field.
func CurrentNodeNotNil() predicate.Execution {
	return predicate.Execution(sql.FieldNotNull(FieldCurrentNode))
}

// CurrentNodeEqualFold applies the EqualFold predicate on the "current_node" field.
func CurrentNodeEqualFold(v string) predicate.Execution {
	return predicate.Execution(sql.FieldEqualFold(FieldCurrentNode, v))
}

// CurrentNodeContainsFold applies the ContainsFold predicate on the "current_node" field.
func CurrentNodeContainsFold(v string) predicate.Execution {
	return predicate.Execution(sql.FieldContainsFold(FieldCurrentNode, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.Execution {
	return predicate.Execution(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.Execution {
	return predicate.Execution(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.Execution {
	return predicate.Execution(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.Execution {
	return predicate.Execution(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.Execution {
	return predicate.Execution(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.Execution {
	return predicate.Execution(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.Execution {
	return predicate.Execution(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.Execution {
	return predicate.Execution(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.Execution {
	return predicate.Execution(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.Execution {
	return predicate.Execution(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.Execution {
	return predicate.Execution(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.Execution {
	return predicate.Execution(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.Execution {
	return predicate.Execution(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.Execution {
	return predicate.Execution(sql.FieldContainsFold(FieldError, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.Execution {
	return predicate.Execution(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.Execution {
	return predicate.Execution(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.Execution {
	return predicate.Execution(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.Execution {
	return predicate.Execution(sql.FieldNotNull(FieldCompletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Execution {
	return predicate.Execution(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGraph applies the HasEdge predicate on the "graph" edge.
func HasGraph() predicate.Execution {
	return predicate.Execution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GraphTable, GraphColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGraphWith applies the HasEdge predicate on the "graph" edge with a given conditions (other predicates).
func HasGraphWith(preds ...predicate.Graph) predicate.Execution {
	return predicate.Execution(func(s *sql.Selector) {
		step := newGraphStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Execution) predicate.Execution {
	return predicate.Execution(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Execution) predicate.Execution {
	return predicate.Execution(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Execution) predicate.Execution {
	return predicate.Execution(sql.NotPredicates(p))
}
