// Code generated by ent, DO NOT EDIT.

package node

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the node type in the database.
	Label = "node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNodeKey holds the string denoting the node_key field in the database.
	FieldNodeKey = "node_key"
	// FieldPattern holds the string denoting the pattern field in the database.
	FieldPattern = "pattern"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeGraph holds the string denoting the graph edge name in mutations.
	EdgeGraph = "graph"
	// Table holds the table name of the node in the database.
	Table = "nodes"
	// GraphTable is the table that holds the graph relation/edge.
	GraphTable = "nodes"
	// GraphInverseTable is the table name for the Graph entity.
	// It exists in this package in order to avoid circular dependency with the "graph" package.
	GraphInverseTable = "graphs"
	// GraphColumn is the table column denoting the graph relation/edge.
	GraphColumn = "graph_nodes"
)

// Columns holds all SQL columns for node fields.
var Columns = []string{
	FieldID,
	FieldNodeKey,
	FieldPattern,
	FieldConfig,
	FieldPosition,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "nodes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"graph_nodes",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NodeKeyValidator is a validator for the "node_key" field. It is called by the builders before save.
	NodeKeyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Pattern defines the type for the "pattern" enum field.
type Pattern string

// Pattern values.
const (
	PatternLlmCall    Pattern = "llm_call"
	PatternToolUse    Pattern = "tool_use"
	PatternReact      Pattern = "react"
	PatternReflection Pattern = "reflection"
	PatternRouter     Pattern = "router"
	PatternGuardrail  Pattern = "guardrail"
	PatternSubgraph   Pattern = "subgraph"
)

func (pa Pattern) String() string {
	return string(pa)
}

// PatternValidator is a validator for the "pattern" field enum values. It is called by the builders before save.
func PatternValidator(pa Pattern) error {
	switch pa {
	case PatternLlmCall, PatternToolUse, PatternReact, PatternReflection, PatternRouter, PatternGuardrail, PatternSubgraph:
		return nil
	default:
		return fmt.Errorf("node: invalid enum value for pattern field: %q", pa)
	}
}

// OrderOption defines the ordering options for the Node queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNodeKey orders the results by the node_key field.
func ByNodeKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeKey, opts...).ToFunc()
}

// ByPattern orders the results by the pattern field.
func ByPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPattern, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGraphField orders the results by graph field.
func ByGraphField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGraphStep(), sql.OrderByField(field, opts...))
	}
}
func newGraphStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GraphInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GraphTable, GraphColumn),
	)
}
