// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ExecutionsColumns holds the columns for the "executions" table.
	ExecutionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "completed", "failed", "cancelled", "interrupted"}, Default: "pending"},
		{Name: "current_node", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "variables", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "messages", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "node_results", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "graph_executions", Type: field.TypeUUID},
	}
	// ExecutionsTable holds the schema information for the "executions" table.
	ExecutionsTable = &schema.Table{
		Name:       "executions",
		Columns:    ExecutionsColumns,
		PrimaryKey: []*schema.Column{ExecutionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "executions_graphs_executions",
				Columns:    []*schema.Column{ExecutionsColumns[11]},
				RefColumns: []*schema.Column{GraphsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "execution_status_graph_executions",
				Unique:  false,
				Columns: []*schema.Column{ExecutionsColumns[1], ExecutionsColumns[11]},
			},
			{
				Name:    "execution_status",
				Unique:  false,
				Columns: []*schema.Column{ExecutionsColumns[1]},
			},
			{
				Name:    "execution_created_at",
				Unique:  false,
				Columns: []*schema.Column{ExecutionsColumns[9]},
			},
		},
	}
	// GraphsColumns holds the columns for the "graphs" table.
	GraphsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "version", Type: field.TypeString, Size: 20},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "entry_node", Type: field.TypeString, Size: 255},
		{Name: "definition", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "memory_config", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "active", "archived"}, Default: "draft"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GraphsTable holds the schema information for the "graphs" table.
	GraphsTable = &schema.Table{
		Name:       "graphs",
		Columns:    GraphsColumns,
		PrimaryKey: []*schema.Column{GraphsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "graph_name_version",
				Unique:  true,
				Columns: []*schema.Column{GraphsColumns[1], GraphsColumns[2]},
			},
			{
				Name:    "graph_status",
				Unique:  false,
				Columns: []*schema.Column{GraphsColumns[7]},
			},
		},
	}
	// NodesColumns holds the columns for the "nodes" table.
	NodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "node_key", Type: field.TypeString, Size: 255},
		{Name: "pattern", Type: field.TypeEnum, Enums: []string{"llm_call", "tool_use", "react", "reflection", "router", "guardrail", "subgraph"}},
		{Name: "config", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "position", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "graph_nodes", Type: field.TypeUUID},
	}
	// NodesTable holds the schema information for the "nodes" table.
	NodesTable = &schema.Table{
		Name:       "nodes",
		Columns:    NodesColumns,
		PrimaryKey: []*schema.Column{NodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "nodes_graphs_nodes",
				Columns:    []*schema.Column{NodesColumns[7]},
				RefColumns: []*schema.Column{GraphsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "node_node_key_graph_nodes",
				Unique:  true,
				Columns: []*schema.Column{NodesColumns[1], NodesColumns[7]},
			},
			{
				Name:    "node_pattern_graph_nodes",
				Unique:  false,
				Columns: []*schema.Column{NodesColumns[2], NodesColumns[7]},
			},
		},
	}
	// OrgUnitsColumns holds the columns for the "org_units" table.
	OrgUnitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "path", Type: field.TypeString, Unique: true, Size: 1024},
		{Name: "tags", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "org_unit_children", Type: field.TypeUUID, Nullable: true},
	}
	// OrgUnitsTable holds the schema information for the "org_units" table.
	OrgUnitsTable = &schema.Table{
		Name:       "org_units",
		Columns:    OrgUnitsColumns,
		PrimaryKey: []*schema.Column{OrgUnitsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "org_units_org_units_children",
				Columns:    []*schema.Column{OrgUnitsColumns[6]},
				RefColumns: []*schema.Column{OrgUnitsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "orgunit_path",
				Unique:  true,
				Columns: []*schema.Column{OrgUnitsColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 320},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "tags", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "org_unit_users", Type: field.TypeUUID, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_org_units_users",
				Columns:    []*schema.Column{UsersColumns[6]},
				RefColumns: []*schema.Column{OrgUnitsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ExecutionsTable,
		GraphsTable,
		NodesTable,
		OrgUnitsTable,
		UsersTable,
	}
)

func init() {
	ExecutionsTable.ForeignKeys[0].RefTable = GraphsTable
	NodesTable.ForeignKeys[0].RefTable = GraphsTable
	OrgUnitsTable.ForeignKeys[0].RefTable = OrgUnitsTable
	UsersTable.ForeignKeys[0].RefTable = OrgUnitsTable
}
