// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/aescanero/dago/ent/migrate"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/aescanero/dago/ent/execution"
	"github.com/aescanero/dago/ent/graph"
	"github.com/aescanero/dago/ent/node"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Execution is the client for interacting with the Execution builders.
	Execution *ExecutionClient
	// Graph is the client for interacting with the Graph builders.
	Graph *GraphClient
	// Node is the client for interacting with the Node builders.
	Node *NodeClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Execution = NewExecutionClient(c.config)
	c.Graph = NewGraphClient(c.config)
	c.Node = NewNodeClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Execution: NewExecutionClient(cfg),
		Graph:     NewGraphClient(cfg),
		Node:      NewNodeClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Execution: NewExecutionClient(cfg),
		Graph:     NewGraphClient(cfg),
		Node:      NewNodeClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Execution.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Execution.Use(hooks...)
	c.Graph.Use(hooks...)
	c.Node.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Execution.Intercept(interceptors...)
	c.Graph.Intercept(interceptors...)
	c.Node.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ExecutionMutation:
		return c.Execution.mutate(ctx, m)
	case *GraphMutation:
		return c.Graph.mutate(ctx, m)
	case *NodeMutation:
		return c.Node.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ExecutionClient is a client for the Execution schema.
type ExecutionClient struct {
	config
}

// NewExecutionClient returns a client for the Execution from the given config.
func NewExecutionClient(c config) *ExecutionClient {
	return &ExecutionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `execution.Hooks(f(g(h())))`.
func (c *ExecutionClient) Use(hooks ...Hook) {
	c.hooks.Execution = append(c.hooks.Execution, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `execution.Intercept(f(g(h())))`.
func (c *ExecutionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Execution = append(c.inters.Execution, interceptors...)
}

// Create returns a builder for creating a Execution entity.
func (c *ExecutionClient) Create() *ExecutionCreate {
	mutation := newExecutionMutation(c.config, OpCreate)
	return &ExecutionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Execution entities.
func (c *ExecutionClient) CreateBulk(builders ...*ExecutionCreate) *ExecutionCreateBulk {
	return &ExecutionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ExecutionClient) MapCreateBulk(slice any, setFunc func(*ExecutionCreate, int)) *ExecutionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ExecutionCreateBulk{err: fmt.Errorf("calling to ExecutionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ExecutionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ExecutionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Execution.
func (c *ExecutionClient) Update() *ExecutionUpdate {
	mutation := newExecutionMutation(c.config, OpUpdate)
	return &ExecutionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ExecutionClient) UpdateOne(_m *Execution) *ExecutionUpdateOne {
	mutation := newExecutionMutation(c.config, OpUpdateOne, withExecution(_m))
	return &ExecutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ExecutionClient) UpdateOneID(id uuid.UUID) *ExecutionUpdateOne {
	mutation := newExecutionMutation(c.config, OpUpdateOne, withExecutionID(id))
	return &ExecutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Execution.
func (c *ExecutionClient) Delete() *ExecutionDelete {
	mutation := newExecutionMutation(c.config, OpDelete)
	return &ExecutionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ExecutionClient) DeleteOne(_m *Execution) *ExecutionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ExecutionClient) DeleteOneID(id uuid.UUID) *ExecutionDeleteOne {
	builder := c.Delete().Where(execution.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ExecutionDeleteOne{builder}
}

// Query returns a query builder for Execution.
func (c *ExecutionClient) Query() *ExecutionQuery {
	return &ExecutionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeExecution},
		inters: c.Interceptors(),
	}
}

// Get returns a Execution entity by its id.
func (c *ExecutionClient) Get(ctx context.Context, id uuid.UUID) (*Execution, error) {
	return c.Query().Where(execution.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ExecutionClient) GetX(ctx context.Context, id uuid.UUID) *Execution {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryGraph queries the graph edge of a Execution.
func (c *ExecutionClient) QueryGraph(_m *Execution) *GraphQuery {
	query := (&GraphClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(execution.Table, execution.FieldID, id),
			sqlgraph.To(graph.Table, graph.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, execution.GraphTable, execution.GraphColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ExecutionClient) Hooks() []Hook {
	return c.hooks.Execution
}

// Interceptors returns the client interceptors.
func (c *ExecutionClient) Interceptors() []Interceptor {
	return c.inters.Execution
}

func (c *ExecutionClient) mutate(ctx context.Context, m *ExecutionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ExecutionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ExecutionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ExecutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ExecutionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Execution mutation op: %q", m.Op())
	}
}

// GraphClient is a client for the Graph schema.
type GraphClient struct {
	config
}

// NewGraphClient returns a client for the Graph from the given config.
func NewGraphClient(c config) *GraphClient {
	return &GraphClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `graph.Hooks(f(g(h())))`.
func (c *GraphClient) Use(hooks ...Hook) {
	c.hooks.Graph = append(c.hooks.Graph, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `graph.Intercept(f(g(h())))`.
func (c *GraphClient) Intercept(interceptors ...Interceptor) {
	c.inters.Graph = append(c.inters.Graph, interceptors...)
}

// Create returns a builder for creating a Graph entity.
func (c *GraphClient) Create() *GraphCreate {
	mutation := newGraphMutation(c.config, OpCreate)
	return &GraphCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Graph entities.
func (c *GraphClient) CreateBulk(builders ...*GraphCreate) *GraphCreateBulk {
	return &GraphCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GraphClient) MapCreateBulk(slice any, setFunc func(*GraphCreate, int)) *GraphCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GraphCreateBulk{err: fmt.Errorf("calling to GraphClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GraphCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GraphCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Graph.
func (c *GraphClient) Update() *GraphUpdate {
	mutation := newGraphMutation(c.config, OpUpdate)
	return &GraphUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GraphClient) UpdateOne(_m *Graph) *GraphUpdateOne {
	mutation := newGraphMutation(c.config, OpUpdateOne, withGraph(_m))
	return &GraphUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GraphClient) UpdateOneID(id uuid.UUID) *GraphUpdateOne {
	mutation := newGraphMutation(c.config, OpUpdateOne, withGraphID(id))
	return &GraphUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Graph.
func (c *GraphClient) Delete() *GraphDelete {
	mutation := newGraphMutation(c.config, OpDelete)
	return &GraphDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GraphClient) DeleteOne(_m *Graph) *GraphDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GraphClient) DeleteOneID(id uuid.UUID) *GraphDeleteOne {
	builder := c.Delete().Where(graph.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GraphDeleteOne{builder}
}

// Query returns a query builder for Graph.
func (c *GraphClient) Query() *GraphQuery {
	return &GraphQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGraph},
		inters: c.Interceptors(),
	}
}

// Get returns a Graph entity by its id.
func (c *GraphClient) Get(ctx context.Context, id uuid.UUID) (*Graph, error) {
	return c.Query().Where(graph.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GraphClient) GetX(ctx context.Context, id uuid.UUID) *Graph {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNodes queries the nodes edge of a Graph.
func (c *GraphClient) QueryNodes(_m *Graph) *NodeQuery {
	query := (&NodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(graph.Table, graph.FieldID, id),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, graph.NodesTable, graph.NodesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryExecutions queries the executions edge of a Graph.
func (c *GraphClient) QueryExecutions(_m *Graph) *ExecutionQuery {
	query := (&ExecutionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(graph.Table, graph.FieldID, id),
			sqlgraph.To(execution.Table, execution.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, graph.ExecutionsTable, graph.ExecutionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GraphClient) Hooks() []Hook {
	return c.hooks.Graph
}

// Interceptors returns the client interceptors.
func (c *GraphClient) Interceptors() []Interceptor {
	return c.inters.Graph
}

func (c *GraphClient) mutate(ctx context.Context, m *GraphMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GraphCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GraphUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GraphUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GraphDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Graph mutation op: %q", m.Op())
	}
}

// NodeClient is a client for the Node schema.
type NodeClient struct {
	config
}

// NewNodeClient returns a client for the Node from the given config.
func NewNodeClient(c config) *NodeClient {
	return &NodeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `node.Hooks(f(g(h())))`.
func (c *NodeClient) Use(hooks ...Hook) {
	c.hooks.Node = append(c.hooks.Node, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `node.Intercept(f(g(h())))`.
func (c *NodeClient) Intercept(interceptors ...Interceptor) {
	c.inters.Node = append(c.inters.Node, interceptors...)
}

// Create returns a builder for creating a Node entity.
func (c *NodeClient) Create() *NodeCreate {
	mutation := newNodeMutation(c.config, OpCreate)
	return &NodeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Node entities.
func (c *NodeClient) CreateBulk(builders ...*NodeCreate) *NodeCreateBulk {
	return &NodeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NodeClient) MapCreateBulk(slice any, setFunc func(*NodeCreate, int)) *NodeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NodeCreateBulk{err: fmt.Errorf("calling to NodeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NodeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NodeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Node.
func (c *NodeClient) Update() *NodeUpdate {
	mutation := newNodeMutation(c.config, OpUpdate)
	return &NodeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NodeClient) UpdateOne(_m *Node) *NodeUpdateOne {
	mutation := newNodeMutation(c.config, OpUpdateOne, withNode(_m))
	return &NodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NodeClient) UpdateOneID(id uuid.UUID) *NodeUpdateOne {
	mutation := newNodeMutation(c.config, OpUpdateOne, withNodeID(id))
	return &NodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Node.
func (c *NodeClient) Delete() *NodeDelete {
	mutation := newNodeMutation(c.config, OpDelete)
	return &NodeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NodeClient) DeleteOne(_m *Node) *NodeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NodeClient) DeleteOneID(id uuid.UUID) *NodeDeleteOne {
	builder := c.Delete().Where(node.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NodeDeleteOne{builder}
}

// Query returns a query builder for Node.
func (c *NodeClient) Query() *NodeQuery {
	return &NodeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNode},
		inters: c.Interceptors(),
	}
}

// Get returns a Node entity by its id.
func (c *NodeClient) Get(ctx context.Context, id uuid.UUID) (*Node, error) {
	return c.Query().Where(node.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NodeClient) GetX(ctx context.Context, id uuid.UUID) *Node {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryGraph queries the graph edge of a Node.
func (c *NodeClient) QueryGraph(_m *Node) *GraphQuery {
	query := (&GraphClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, id),
			sqlgraph.To(graph.Table, graph.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, node.GraphTable, node.GraphColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NodeClient) Hooks() []Hook {
	return c.hooks.Node
}

// Interceptors returns the client interceptors.
func (c *NodeClient) Interceptors() []Interceptor {
	return c.inters.Node
}

func (c *NodeClient) mutate(ctx context.Context, m *NodeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NodeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NodeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NodeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Node mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Execution, Graph, Node []ent.Hook
	}
	inters struct {
		Execution, Graph, Node []ent.Interceptor
	}
)
