// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aescanero/dago/ent/execution"
	"github.com/aescanero/dago/ent/graph"
	"github.com/google/uuid"
)

// ExecutionCreate is the builder for creating a Execution entity.
type ExecutionCreate struct {
	config
	mutation *ExecutionMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *ExecutionCreate) SetStatus(v execution.Status) *ExecutionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableStatus(v *execution.Status) *ExecutionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCurrentNode sets the "current_node" field.
func (_c *ExecutionCreate) SetCurrentNode(v string) *ExecutionCreate {
	_c.mutation.SetCurrentNode(v)
	return _c
}

// SetNillableCurrentNode sets the "current_node" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableCurrentNode(v *string) *ExecutionCreate {
	if v != nil {
		_c.SetCurrentNode(*v)
	}
	return _c
}

// SetVariables sets the "variables" field.
func (_c *ExecutionCreate) SetVariables(v json.RawMessage) *ExecutionCreate {
	_c.mutation.SetVariables(v)
	return _c
}

// SetMessages sets the "messages" field.
func (_c *ExecutionCreate) SetMessages(v json.RawMessage) *ExecutionCreate {
	_c.mutation.SetMessages(v)
	return _c
}

// SetNodeResults sets the "node_results" field.
func (_c *ExecutionCreate) SetNodeResults(v json.RawMessage) *ExecutionCreate {
	_c.mutation.SetNodeResults(v)
	return _c
}

// SetError sets the "error" field.
func (_c *ExecutionCreate) SetError(v string) *ExecutionCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableError(v *string) *ExecutionCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *ExecutionCreate) SetStartedAt(v time.Time) *ExecutionCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableStartedAt(v *time.Time) *ExecutionCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *ExecutionCreate) SetCompletedAt(v time.Time) *ExecutionCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableCompletedAt(v *time.Time) *ExecutionCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExecutionCreate) SetCreatedAt(v time.Time) *ExecutionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableCreatedAt(v *time.Time) *ExecutionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExecutionCreate) SetUpdatedAt(v time.Time) *ExecutionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableUpdatedAt(v *time.Time) *ExecutionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExecutionCreate) SetID(v uuid.UUID) *ExecutionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ExecutionCreate) SetNillableID(v *uuid.UUID) *ExecutionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGraphID sets the "graph" edge to the Graph entity by ID.
func (_c *ExecutionCreate) SetGraphID(id uuid.UUID) *ExecutionCreate {
	_c.mutation.SetGraphID(id)
	return _c
}

// SetGraph sets the "graph" edge to the Graph entity.
func (_c *ExecutionCreate) SetGraph(v *Graph) *ExecutionCreate {
	return _c.SetGraphID(v.ID)
}

// Mutation returns the ExecutionMutation object of the builder.
func (_c *ExecutionCreate) Mutation() *ExecutionMutation {
	return _c.mutation
}

// Save creates the Execution in the database.
func (_c *ExecutionCreate) Save(ctx context.Context) (*Execution, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExecutionCreate) SaveX(ctx context.Context) *Execution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExecutionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExecutionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExecutionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := execution.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Variables(); !ok {
		v := execution.DefaultVariables
		_c.mutation.SetVariables(v)
	}
	if _, ok := _c.mutation.Messages(); !ok {
		v := execution.DefaultMessages
		_c.mutation.SetMessages(v)
	}
	if _, ok := _c.mutation.NodeResults(); !ok {
		v := execution.DefaultNodeResults
		_c.mutation.SetNodeResults(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := execution.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := execution.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := execution.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExecutionCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Execution.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := execution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Execution.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CurrentNode(); ok {
		if err := execution.CurrentNodeValidator(v); err != nil {
			return &ValidationError{Name: "current_node", err: fmt.Errorf(`ent: validator failed for field "Execution.current_node": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Variables(); !ok {
		return &ValidationError{Name: "variables", err: errors.New(`ent: missing required field "Execution.variables"`)}
	}
	if _, ok := _c.mutation.Messages(); !ok {
		return &ValidationError{Name: "messages", err: errors.New(`ent: missing required field "Execution.messages"`)}
	}
	if _, ok := _c.mutation.NodeResults(); !ok {
		return &ValidationError{Name: "node_results", err: errors.New(`ent: missing required field "Execution.node_results"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Execution.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Execution.updated_at"`)}
	}
	if len(_c.mutation.GraphIDs()) == 0 {
		return &ValidationError{Name: "graph", err: errors.New(`ent: missing required edge "Execution.graph"`)}
	}
	return nil
}

func (_c *ExecutionCreate) sqlSave(ctx context.Context) (*Execution, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExecutionCreate) createSpec() (*Execution, *sqlgraph.CreateSpec) {
	var (
		_node = &Execution{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(execution.Table, sqlgraph.NewFieldSpec(execution.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(execution.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CurrentNode(); ok {
		_spec.SetField(execution.FieldCurrentNode, field.TypeString, value)
		_node.CurrentNode = &value
	}
	if value, ok := _c.mutation.Variables(); ok {
		_spec.SetField(execution.FieldVariables, field.TypeJSON, value)
		_node.Variables = value
	}
	if value, ok := _c.mutation.Messages(); ok {
		_spec.SetField(execution.FieldMessages, field.TypeJSON, value)
		_node.Messages = value
	}
	if value, ok := _c.mutation.NodeResults(); ok {
		_spec.SetField(execution.FieldNodeResults, field.TypeJSON, value)
		_node.NodeResults = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(execution.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(execution.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(execution.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(execution.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(execution.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.GraphIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   execution.GraphTable,
			Columns: []string{execution.GraphColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(graph.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.graph_executions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ExecutionCreateBulk is the builder for creating many Execution entities in bulk.
type ExecutionCreateBulk struct {
	config
	err      error
	builders []*ExecutionCreate
}

// Save creates the Execution entities in the database.
func (_c *ExecutionCreateBulk) Save(ctx context.Context) ([]*Execution, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Execution, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExecutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExecutionCreateBulk) SaveX(ctx context.Context) []*Execution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExecutionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExecutionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
