// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/aescanero/dago/ent/execution"
	"github.com/aescanero/dago/ent/graph"
	"github.com/google/uuid"
)

// Execution is the model entity for the Execution schema.
type Execution struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status execution.Status `json:"status,omitempty"`
	// CurrentNode holds the value of the "current_node" field.
	CurrentNode *string `json:"current_node,omitempty"`
	// Variables holds the value of the "variables" field.
	Variables json.RawMessage `json:"variables,omitempty"`
	// Messages holds the value of the "messages" field.
	Messages json.RawMessage `json:"messages,omitempty"`
	// NodeResults holds the value of the "node_results" field.
	NodeResults json.RawMessage `json:"node_results,omitempty"`
	// Error holds the value of the "error" field.
	Error *string `json:"error,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExecutionQuery when eager-loading is set.
	Edges            ExecutionEdges `json:"edges"`
	graph_executions *uuid.UUID
	selectValues     sql.SelectValues
}

// ExecutionEdges holds the relations/edges for other nodes in the graph.
type ExecutionEdges struct {
	// Graph holds the value of the graph edge.
	Graph *Graph `json:"graph,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GraphOrErr returns the Graph value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ExecutionEdges) GraphOrErr() (*Graph, error) {
	if e.Graph != nil {
		return e.Graph, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: graph.Label}
	}
	return nil, &NotLoadedError{edge: "graph"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Execution) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case execution.FieldVariables, execution.FieldMessages, execution.FieldNodeResults:
			values[i] = new([]byte)
		case execution.FieldStatus, execution.FieldCurrentNode, execution.FieldError:
			values[i] = new(sql.NullString)
		case execution.FieldStartedAt, execution.FieldCompletedAt, execution.FieldCreatedAt, execution.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case execution.FieldID:
			values[i] = new(uuid.UUID)
		case execution.ForeignKeys[0]: // graph_executions
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Execution fields.
func (_m *Execution) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case execution.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case execution.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = execution.Status(value.String)
			}
		case execution.FieldCurrentNode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_node", values[i])
			} else if value.Valid {
				_m.CurrentNode = new(string)
				*_m.CurrentNode = value.String
			}
		case execution.FieldVariables:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field variables", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Variables); err != nil {
					return fmt.Errorf("unmarshal field variables: %w", err)
				}
			}
		case execution.FieldMessages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field messages", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Messages); err != nil {
					return fmt.Errorf("unmarshal field messages: %w", err)
				}
			}
		case execution.FieldNodeResults:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field node_results", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.NodeResults); err != nil {
					return fmt.Errorf("unmarshal field node_results: %w", err)
				}
			}
		case execution.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = new(string)
				*_m.Error = value.String
			}
		case execution.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case execution.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case execution.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case execution.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case execution.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field graph_executions", values[i])
			} else if value.Valid {
				_m.graph_executions = new(uuid.UUID)
				*_m.graph_executions = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Execution.
// This includes values selected through modifiers, order, etc.
func (_m *Execution) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGraph queries the "graph" edge of the Execution entity.
func (_m *Execution) QueryGraph() *GraphQuery {
	return NewExecutionClient(_m.config).QueryGraph(_m)
}

// Update returns a builder for updating this Execution.
// Note that you need to call Execution.Unwrap() before calling this method if this Execution
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Execution) Update() *ExecutionUpdateOne {
	return NewExecutionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Execution entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Execution) Unwrap() *Execution {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Execution is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Execution) String() string {
	var builder strings.Builder
	builder.WriteString("Execution(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.CurrentNode; v != nil {
		builder.WriteString("current_node=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("variables=")
	builder.WriteString(fmt.Sprintf("%v", _m.Variables))
	builder.WriteString(", ")
	builder.WriteString("messages=")
	builder.WriteString(fmt.Sprintf("%v", _m.Messages))
	builder.WriteString(", ")
	builder.WriteString("node_results=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodeResults))
	builder.WriteString(", ")
	if v := _m.Error; v != nil {
		builder.WriteString("error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Executions is a parsable slice of Execution.
type Executions []*Execution
