// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/aescanero/dago/ent/execution"
	"github.com/aescanero/dago/ent/graph"
	"github.com/aescanero/dago/ent/predicate"
	"github.com/google/uuid"
)

// ExecutionUpdate is the builder for updating Execution entities.
type ExecutionUpdate struct {
	config
	hooks    []Hook
	mutation *ExecutionMutation
}

// Where appends a list predicates to the ExecutionUpdate builder.
func (_u *ExecutionUpdate) Where(ps ...predicate.Execution) *ExecutionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ExecutionUpdate) SetStatus(v execution.Status) *ExecutionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ExecutionUpdate) SetNillableStatus(v *execution.Status) *ExecutionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentNode sets the "current_node" field.
func (_u *ExecutionUpdate) SetCurrentNode(v string) *ExecutionUpdate {
	_u.mutation.SetCurrentNode(v)
	return _u
}

// SetNillableCurrentNode sets the "current_node" field if the given value is not nil.
func (_u *ExecutionUpdate) SetNillableCurrentNode(v *string) *ExecutionUpdate {
	if v != nil {
		_u.SetCurrentNode(*v)
	}
	return _u
}

// ClearCurrentNode clears the value of the "current_node" field.
func (_u *ExecutionUpdate) ClearCurrentNode() *ExecutionUpdate {
	_u.mutation.ClearCurrentNode()
	return _u
}

// SetVariables sets the "variables" field.
func (_u *ExecutionUpdate) SetVariables(v json.RawMessage) *ExecutionUpdate {
	_u.mutation.SetVariables(v)
	return _u
}

// AppendVariables appends value to the "variables" field.
func (_u *ExecutionUpdate) AppendVariables(v json.RawMessage) *ExecutionUpdate {
	_u.mutation.AppendVariables(v)
	return _u
}

// SetMessages sets the "messages" field.
func (_u *ExecutionUpdate) SetMessages(v json.RawMessage) *ExecutionUpdate {
	_u.mutation.SetMessages(v)
	return _u
}

// AppendMessages appends value to the "messages" field.
func (_u *ExecutionUpdate) AppendMessages(v json.RawMessage) *ExecutionUpdate {
	_u.mutation.AppendMessages(v)
	return _u
}

// SetNodeResults sets the "node_results" field.
func (_u *ExecutionUpdate) SetNodeResults(v json.RawMessage) *ExecutionUpdate {
	_u.mutation.SetNodeResults(v)
	return _u
}

// AppendNodeResults appends value to the "node_results" field.
func (_u *ExecutionUpdate) AppendNodeResults(v json.RawMessage) *ExecutionUpdate {
	_u.mutation.AppendNodeResults(v)
	return _u
}

// SetError sets the "error" field.
func (_u *ExecutionUpdate) SetError(v string) *ExecutionUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ExecutionUpdate) SetNillableError(v *string) *ExecutionUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *ExecutionUpdate) ClearError() *ExecutionUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ExecutionUpdate) SetStartedAt(v time.Time) *ExecutionUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ExecutionUpdate) SetNillableStartedAt(v *time.Time) *ExecutionUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ExecutionUpdate) ClearStartedAt() *ExecutionUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ExecutionUpdate) SetCompletedAt(v time.Time) *ExecutionUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ExecutionUpdate) SetNillableCompletedAt(v *time.Time) *ExecutionUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ExecutionUpdate) ClearCompletedAt() *ExecutionUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExecutionUpdate) SetUpdatedAt(v time.Time) *ExecutionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGraphID sets the "graph" edge to the Graph entity by ID.
func (_u *ExecutionUpdate) SetGraphID(id uuid.UUID) *ExecutionUpdate {
	_u.mutation.SetGraphID(id)
	return _u
}

// SetGraph sets the "graph" edge to the Graph entity.
func (_u *ExecutionUpdate) SetGraph(v *Graph) *ExecutionUpdate {
	return _u.SetGraphID(v.ID)
}

// Mutation returns the ExecutionMutation object of the builder.
func (_u *ExecutionUpdate) Mutation() *ExecutionMutation {
	return _u.mutation
}

// ClearGraph clears the "graph" edge to the Graph entity.
func (_u *ExecutionUpdate) ClearGraph() *ExecutionUpdate {
	_u.mutation.ClearGraph()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExecutionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExecutionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExecutionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExecutionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExecutionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := execution.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExecutionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := execution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Execution.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentNode(); ok {
		if err := execution.CurrentNodeValidator(v); err != nil {
			return &ValidationError{Name: "current_node", err: fmt.Errorf(`ent: validator failed for field "Execution.current_node": %w`, err)}
		}
	}
	if _u.mutation.GraphCleared() && len(_u.mutation.GraphIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Execution.graph"`)
	}
	return nil
}

func (_u *ExecutionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(execution.Table, execution.Columns, sqlgraph.NewFieldSpec(execution.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(execution.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentNode(); ok {
		_spec.SetField(execution.FieldCurrentNode, field.TypeString, value)
	}
	if _u.mutation.CurrentNodeCleared() {
		_spec.ClearField(execution.FieldCurrentNode, field.TypeString)
	}
	if value, ok := _u.mutation.Variables(); ok {
		_spec.SetField(execution.FieldVariables, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVariables(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, execution.FieldVariables, value)
		})
	}
	if value, ok := _u.mutation.Messages(); ok {
		_spec.SetField(execution.FieldMessages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMessages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, execution.FieldMessages, value)
		})
	}
	if value, ok := _u.mutation.NodeResults(); ok {
		_spec.SetField(execution.FieldNodeResults, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNodeResults(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, execution.FieldNodeResults, value)
		})
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(execution.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(execution.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(execution.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(execution.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(execution.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(execution.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(execution.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GraphCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   execution.GraphTable,
			Columns: []string{execution.GraphColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(graph.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GraphIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   execution.GraphTable,
			Columns: []string{execution.GraphColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(graph.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{execution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExecutionUpdateOne is the builder for updating a single Execution entity.
type ExecutionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExecutionMutation
}

// SetStatus sets the "status" field.
func (_u *ExecutionUpdateOne) SetStatus(v execution.Status) *ExecutionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ExecutionUpdateOne) SetNillableStatus(v *execution.Status) *ExecutionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentNode sets the "current_node" field.
func (_u *ExecutionUpdateOne) SetCurrentNode(v string) *ExecutionUpdateOne {
	_u.mutation.SetCurrentNode(v)
	return _u
}

// SetNillableCurrentNode sets the "current_node" field if the given value is not nil.
func (_u *ExecutionUpdateOne) SetNillableCurrentNode(v *string) *ExecutionUpdateOne {
	if v != nil {
		_u.SetCurrentNode(*v)
	}
	return _u
}

// ClearCurrentNode clears the value of the "current_node" field.
func (_u *ExecutionUpdateOne) ClearCurrentNode() *ExecutionUpdateOne {
	_u.mutation.ClearCurrentNode()
	return _u
}

// SetVariables sets the "variables" field.
func (_u *ExecutionUpdateOne) SetVariables(v json.RawMessage) *ExecutionUpdateOne {
	_u.mutation.SetVariables(v)
	return _u
}

// AppendVariables appends value to the "variables" field.
func (_u *ExecutionUpdateOne) AppendVariables(v json.RawMessage) *ExecutionUpdateOne {
	_u.mutation.AppendVariables(v)
	return _u
}

// SetMessages sets the "messages" field.
func (_u *ExecutionUpdateOne) SetMessages(v json.RawMessage) *ExecutionUpdateOne {
	_u.mutation.SetMessages(v)
	return _u
}

// AppendMessages appends value to the "messages" field.
func (_u *ExecutionUpdateOne) AppendMessages(v json.RawMessage) *ExecutionUpdateOne {
	_u.mutation.AppendMessages(v)
	return _u
}

// SetNodeResults sets the "node_results" field.
func (_u *ExecutionUpdateOne) SetNodeResults(v json.RawMessage) *ExecutionUpdateOne {
	_u.mutation.SetNodeResults(v)
	return _u
}

// AppendNodeResults appends value to the "node_results" field.
func (_u *ExecutionUpdateOne) AppendNodeResults(v json.RawMessage) *ExecutionUpdateOne {
	_u.mutation.AppendNodeResults(v)
	return _u
}

// SetError sets the "error" field.
func (_u *ExecutionUpdateOne) SetError(v string) *ExecutionUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ExecutionUpdateOne) SetNillableError(v *string) *ExecutionUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *ExecutionUpdateOne) ClearError() *ExecutionUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ExecutionUpdateOne) SetStartedAt(v time.Time) *ExecutionUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ExecutionUpdateOne) SetNillableStartedAt(v *time.Time) *ExecutionUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ExecutionUpdateOne) ClearStartedAt() *ExecutionUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ExecutionUpdateOne) SetCompletedAt(v time.Time) *ExecutionUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ExecutionUpdateOne) SetNillableCompletedAt(v *time.Time) *ExecutionUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ExecutionUpdateOne) ClearCompletedAt() *ExecutionUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExecutionUpdateOne) SetUpdatedAt(v time.Time) *ExecutionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGraphID sets the "graph" edge to the Graph entity by ID.
func (_u *ExecutionUpdateOne) SetGraphID(id uuid.UUID) *ExecutionUpdateOne {
	_u.mutation.SetGraphID(id)
	return _u
}

// SetGraph sets the "graph" edge to the Graph entity.
func (_u *ExecutionUpdateOne) SetGraph(v *Graph) *ExecutionUpdateOne {
	return _u.SetGraphID(v.ID)
}

// Mutation returns the ExecutionMutation object of the builder.
func (_u *ExecutionUpdateOne) Mutation() *ExecutionMutation {
	return _u.mutation
}

// ClearGraph clears the "graph" edge to the Graph entity.
func (_u *ExecutionUpdateOne) ClearGraph() *ExecutionUpdateOne {
	_u.mutation.ClearGraph()
	return _u
}

// Where appends a list predicates to the ExecutionUpdate builder.
func (_u *ExecutionUpdateOne) Where(ps ...predicate.Execution) *ExecutionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExecutionUpdateOne) Select(field string, fields ...string) *ExecutionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Execution entity.
func (_u *ExecutionUpdateOne) Save(ctx context.Context) (*Execution, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExecutionUpdateOne) SaveX(ctx context.Context) *Execution {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExecutionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExecutionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExecutionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := execution.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExecutionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := execution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Execution.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentNode(); ok {
		if err := execution.CurrentNodeValidator(v); err != nil {
			return &ValidationError{Name: "current_node", err: fmt.Errorf(`ent: validator failed for field "Execution.current_node": %w`, err)}
		}
	}
	if _u.mutation.GraphCleared() && len(_u.mutation.GraphIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Execution.graph"`)
	}
	return nil
}

func (_u *ExecutionUpdateOne) sqlSave(ctx context.Context) (_node *Execution, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(execution.Table, execution.Columns, sqlgraph.NewFieldSpec(execution.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Execution.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, execution.FieldID)
		for _, f := range fields {
			if !execution.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != execution.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(execution.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentNode(); ok {
		_spec.SetField(execution.FieldCurrentNode, field.TypeString, value)
	}
	if _u.mutation.CurrentNodeCleared() {
		_spec.ClearField(execution.FieldCurrentNode, field.TypeString)
	}
	if value, ok := _u.mutation.Variables(); ok {
		_spec.SetField(execution.FieldVariables, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVariables(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, execution.FieldVariables, value)
		})
	}
	if value, ok := _u.mutation.Messages(); ok {
		_spec.SetField(execution.FieldMessages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMessages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, execution.FieldMessages, value)
		})
	}
	if value, ok := _u.mutation.NodeResults(); ok {
		_spec.SetField(execution.FieldNodeResults, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNodeResults(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, execution.FieldNodeResults, value)
		})
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(execution.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(execution.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(execution.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(execution.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(execution.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(execution.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(execution.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GraphCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   execution.GraphTable,
			Columns: []string{execution.GraphColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(graph.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GraphIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   execution.GraphTable,
			Columns: []string{execution.GraphColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(graph.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Execution{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{execution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
