// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aescanero/dago/ent/execution"
	"github.com/aescanero/dago/ent/graph"
	"github.com/aescanero/dago/ent/node"
	"github.com/google/uuid"
)

// GraphCreate is the builder for creating a Graph entity.
type GraphCreate struct {
	config
	mutation *GraphMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *GraphCreate) SetName(v string) *GraphCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *GraphCreate) SetVersion(v string) *GraphCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *GraphCreate) SetDescription(v string) *GraphCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *GraphCreate) SetNillableDescription(v *string) *GraphCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEntryNode sets the "entry_node" field.
func (_c *GraphCreate) SetEntryNode(v string) *GraphCreate {
	_c.mutation.SetEntryNode(v)
	return _c
}

// SetDefinition sets the "definition" field.
func (_c *GraphCreate) SetDefinition(v json.RawMessage) *GraphCreate {
	_c.mutation.SetDefinition(v)
	return _c
}

// SetMemoryConfig sets the "memory_config" field.
func (_c *GraphCreate) SetMemoryConfig(v json.RawMessage) *GraphCreate {
	_c.mutation.SetMemoryConfig(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *GraphCreate) SetStatus(v graph.Status) *GraphCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GraphCreate) SetNillableStatus(v *graph.Status) *GraphCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GraphCreate) SetCreatedAt(v time.Time) *GraphCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GraphCreate) SetNillableCreatedAt(v *time.Time) *GraphCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GraphCreate) SetUpdatedAt(v time.Time) *GraphCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GraphCreate) SetNillableUpdatedAt(v *time.Time) *GraphCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GraphCreate) SetID(v uuid.UUID) *GraphCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GraphCreate) SetNillableID(v *uuid.UUID) *GraphCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddNodeIDs adds the "nodes" edge to the Node entity by IDs.
func (_c *GraphCreate) AddNodeIDs(ids ...uuid.UUID) *GraphCreate {
	_c.mutation.AddNodeIDs(ids...)
	return _c
}

// AddNodes adds the "nodes" edges to the Node entity.
func (_c *GraphCreate) AddNodes(v ...*Node) *GraphCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNodeIDs(ids...)
}

// AddExecutionIDs adds the "executions" edge to the Execution entity by IDs.
func (_c *GraphCreate) AddExecutionIDs(ids ...uuid.UUID) *GraphCreate {
	_c.mutation.AddExecutionIDs(ids...)
	return _c
}

// AddExecutions adds the "executions" edges to the Execution entity.
func (_c *GraphCreate) AddExecutions(v ...*Execution) *GraphCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddExecutionIDs(ids...)
}

// Mutation returns the GraphMutation object of the builder.
func (_c *GraphCreate) Mutation() *GraphMutation {
	return _c.mutation
}

// Save creates the Graph in the database.
func (_c *GraphCreate) Save(ctx context.Context) (*Graph, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GraphCreate) SaveX(ctx context.Context) *Graph {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GraphCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GraphCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GraphCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := graph.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := graph.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := graph.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := graph.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GraphCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Graph.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := graph.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Graph.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Graph.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := graph.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Graph.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EntryNode(); !ok {
		return &ValidationError{Name: "entry_node", err: errors.New(`ent: missing required field "Graph.entry_node"`)}
	}
	if v, ok := _c.mutation.EntryNode(); ok {
		if err := graph.EntryNodeValidator(v); err != nil {
			return &ValidationError{Name: "entry_node", err: fmt.Errorf(`ent: validator failed for field "Graph.entry_node": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Definition(); !ok {
		return &ValidationError{Name: "definition", err: errors.New(`ent: missing required field "Graph.definition"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Graph.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := graph.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Graph.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Graph.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Graph.updated_at"`)}
	}
	return nil
}

func (_c *GraphCreate) sqlSave(ctx context.Context) (*Graph, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GraphCreate) createSpec() (*Graph, *sqlgraph.CreateSpec) {
	var (
		_node = &Graph{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(graph.Table, sqlgraph.NewFieldSpec(graph.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(graph.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(graph.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(graph.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.EntryNode(); ok {
		_spec.SetField(graph.FieldEntryNode, field.TypeString, value)
		_node.EntryNode = value
	}
	if value, ok := _c.mutation.Definition(); ok {
		_spec.SetField(graph.FieldDefinition, field.TypeJSON, value)
		_node.Definition = value
	}
	if value, ok := _c.mutation.MemoryConfig(); ok {
		_spec.SetField(graph.FieldMemoryConfig, field.TypeJSON, value)
		_node.MemoryConfig = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(graph.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(graph.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(graph.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.NodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   graph.NodesTable,
			Columns: []string{graph.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   graph.ExecutionsTable,
			Columns: []string{graph.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(execution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GraphCreateBulk is the builder for creating many Graph entities in bulk.
type GraphCreateBulk struct {
	config
	err      error
	builders []*GraphCreate
}

// Save creates the Graph entities in the database.
func (_c *GraphCreateBulk) Save(ctx context.Context) ([]*Graph, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Graph, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GraphMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GraphCreateBulk) SaveX(ctx context.Context) []*Graph {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GraphCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GraphCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
