// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/aescanero/dago/ent/graph"
	"github.com/google/uuid"
)

// Graph is the model entity for the Graph schema.
type Graph struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// EntryNode holds the value of the "entry_node" field.
	EntryNode string `json:"entry_node,omitempty"`
	// Definition holds the value of the "definition" field.
	Definition json.RawMessage `json:"definition,omitempty"`
	// MemoryConfig holds the value of the "memory_config" field.
	MemoryConfig json.RawMessage `json:"memory_config,omitempty"`
	// Status holds the value of the "status" field.
	Status graph.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GraphQuery when eager-loading is set.
	Edges        GraphEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GraphEdges holds the relations/edges for other nodes in the graph.
type GraphEdges struct {
	// Nodes holds the value of the nodes edge.
	Nodes []*Node `json:"nodes,omitempty"`
	// Executions holds the value of the executions edge.
	Executions []*Execution `json:"executions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// NodesOrErr returns the Nodes value or an error if the edge
// was not loaded in eager-loading.
func (e GraphEdges) NodesOrErr() ([]*Node, error) {
	if e.loadedTypes[0] {
		return e.Nodes, nil
	}
	return nil, &NotLoadedError{edge: "nodes"}
}

// ExecutionsOrErr returns the Executions value or an error if the edge
// was not loaded in eager-loading.
func (e GraphEdges) ExecutionsOrErr() ([]*Execution, error) {
	if e.loadedTypes[1] {
		return e.Executions, nil
	}
	return nil, &NotLoadedError{edge: "executions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Graph) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case graph.FieldDefinition, graph.FieldMemoryConfig:
			values[i] = new([]byte)
		case graph.FieldName, graph.FieldVersion, graph.FieldDescription, graph.FieldEntryNode, graph.FieldStatus:
			values[i] = new(sql.NullString)
		case graph.FieldCreatedAt, graph.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case graph.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Graph fields.
func (_m *Graph) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case graph.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case graph.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case graph.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case graph.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case graph.FieldEntryNode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entry_node", values[i])
			} else if value.Valid {
				_m.EntryNode = value.String
			}
		case graph.FieldDefinition:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field definition", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Definition); err != nil {
					return fmt.Errorf("unmarshal field definition: %w", err)
				}
			}
		case graph.FieldMemoryConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field memory_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MemoryConfig); err != nil {
					return fmt.Errorf("unmarshal field memory_config: %w", err)
				}
			}
		case graph.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = graph.Status(value.String)
			}
		case graph.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case graph.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Graph.
// This includes values selected through modifiers, order, etc.
func (_m *Graph) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryNodes queries the "nodes" edge of the Graph entity.
func (_m *Graph) QueryNodes() *NodeQuery {
	return NewGraphClient(_m.config).QueryNodes(_m)
}

// QueryExecutions queries the "executions" edge of the Graph entity.
func (_m *Graph) QueryExecutions() *ExecutionQuery {
	return NewGraphClient(_m.config).QueryExecutions(_m)
}

// Update returns a builder for updating this Graph.
// Note that you need to call Graph.Unwrap() before calling this method if this Graph
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Graph) Update() *GraphUpdateOne {
	return NewGraphClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Graph entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Graph) Unwrap() *Graph {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Graph is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Graph) String() string {
	var builder strings.Builder
	builder.WriteString("Graph(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("entry_node=")
	builder.WriteString(_m.EntryNode)
	builder.WriteString(", ")
	builder.WriteString("definition=")
	builder.WriteString(fmt.Sprintf("%v", _m.Definition))
	builder.WriteString(", ")
	builder.WriteString("memory_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.MemoryConfig))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Graphs is a parsable slice of Graph.
type Graphs []*Graph
