// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/aescanero/dago/ent/execution"
	"github.com/aescanero/dago/ent/graph"
	"github.com/aescanero/dago/ent/node"
	"github.com/aescanero/dago/ent/predicate"
	"github.com/google/uuid"
)

// GraphUpdate is the builder for updating Graph entities.
type GraphUpdate struct {
	config
	hooks    []Hook
	mutation *GraphMutation
}

// Where appends a list predicates to the GraphUpdate builder.
func (_u *GraphUpdate) Where(ps ...predicate.Graph) *GraphUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *GraphUpdate) SetName(v string) *GraphUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GraphUpdate) SetNillableName(v *string) *GraphUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *GraphUpdate) SetVersion(v string) *GraphUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *GraphUpdate) SetNillableVersion(v *string) *GraphUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GraphUpdate) SetDescription(v string) *GraphUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GraphUpdate) SetNillableDescription(v *string) *GraphUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GraphUpdate) ClearDescription() *GraphUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetEntryNode sets the "entry_node" field.
func (_u *GraphUpdate) SetEntryNode(v string) *GraphUpdate {
	_u.mutation.SetEntryNode(v)
	return _u
}

// SetNillableEntryNode sets the "entry_node" field if the given value is not nil.
func (_u *GraphUpdate) SetNillableEntryNode(v *string) *GraphUpdate {
	if v != nil {
		_u.SetEntryNode(*v)
	}
	return _u
}

// SetDefinition sets the "definition" field.
func (_u *GraphUpdate) SetDefinition(v json.RawMessage) *GraphUpdate {
	_u.mutation.SetDefinition(v)
	return _u
}

// AppendDefinition appends value to the "definition" field.
func (_u *GraphUpdate) AppendDefinition(v json.RawMessage) *GraphUpdate {
	_u.mutation.AppendDefinition(v)
	return _u
}

// SetMemoryConfig sets the "memory_config" field.
func (_u *GraphUpdate) SetMemoryConfig(v json.RawMessage) *GraphUpdate {
	_u.mutation.SetMemoryConfig(v)
	return _u
}

// AppendMemoryConfig appends value to the "memory_config" field.
func (_u *GraphUpdate) AppendMemoryConfig(v json.RawMessage) *GraphUpdate {
	_u.mutation.AppendMemoryConfig(v)
	return _u
}

// ClearMemoryConfig clears the value of the "memory_config" field.
func (_u *GraphUpdate) ClearMemoryConfig() *GraphUpdate {
	_u.mutation.ClearMemoryConfig()
	return _u
}

// SetStatus sets the "status" field.
func (_u *GraphUpdate) SetStatus(v graph.Status) *GraphUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GraphUpdate) SetNillableStatus(v *graph.Status) *GraphUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GraphUpdate) SetUpdatedAt(v time.Time) *GraphUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddNodeIDs adds the "nodes" edge to the Node entity by IDs.
func (_u *GraphUpdate) AddNodeIDs(ids ...uuid.UUID) *GraphUpdate {
	_u.mutation.AddNodeIDs(ids...)
	return _u
}

// AddNodes adds the "nodes" edges to the Node entity.
func (_u *GraphUpdate) AddNodes(v ...*Node) *GraphUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNodeIDs(ids...)
}

// AddExecutionIDs adds the "executions" edge to the Execution entity by IDs.
func (_u *GraphUpdate) AddExecutionIDs(ids ...uuid.UUID) *GraphUpdate {
	_u.mutation.AddExecutionIDs(ids...)
	return _u
}

// AddExecutions adds the "executions" edges to the Execution entity.
func (_u *GraphUpdate) AddExecutions(v ...*Execution) *GraphUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExecutionIDs(ids...)
}

// Mutation returns the GraphMutation object of the builder.
func (_u *GraphUpdate) Mutation() *GraphMutation {
	return _u.mutation
}

// ClearNodes clears all "nodes" edges to the Node entity.
func (_u *GraphUpdate) ClearNodes() *GraphUpdate {
	_u.mutation.ClearNodes()
	return _u
}

// RemoveNodeIDs removes the "nodes" edge to Node entities by IDs.
func (_u *GraphUpdate) RemoveNodeIDs(ids ...uuid.UUID) *GraphUpdate {
	_u.mutation.RemoveNodeIDs(ids...)
	return _u
}

// RemoveNodes removes "nodes" edges to Node entities.
func (_u *GraphUpdate) RemoveNodes(v ...*Node) *GraphUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNodeIDs(ids...)
}

// ClearExecutions clears all "executions" edges to the Execution entity.
func (_u *GraphUpdate) ClearExecutions() *GraphUpdate {
	_u.mutation.ClearExecutions()
	return _u
}

// RemoveExecutionIDs removes the "executions" edge to Execution entities by IDs.
func (_u *GraphUpdate) RemoveExecutionIDs(ids ...uuid.UUID) *GraphUpdate {
	_u.mutation.RemoveExecutionIDs(ids...)
	return _u
}

// RemoveExecutions removes "executions" edges to Execution entities.
func (_u *GraphUpdate) RemoveExecutions(v ...*Execution) *GraphUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExecutionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GraphUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GraphUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GraphUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GraphUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GraphUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := graph.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GraphUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := graph.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Graph.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := graph.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Graph.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntryNode(); ok {
		if err := graph.EntryNodeValidator(v); err != nil {
			return &ValidationError{Name: "entry_node", err: fmt.Errorf(`ent: validator failed for field "Graph.entry_node": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := graph.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Graph.status": %w`, err)}
		}
	}
	return nil
}

func (_u *GraphUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(graph.Table, graph.Columns, sqlgraph.NewFieldSpec(graph.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(graph.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(graph.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(graph.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(graph.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.EntryNode(); ok {
		_spec.SetField(graph.FieldEntryNode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Definition(); ok {
		_spec.SetField(graph.FieldDefinition, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDefinition(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, graph.FieldDefinition, value)
		})
	}
	if value, ok := _u.mutation.MemoryConfig(); ok {
		_spec.SetField(graph.FieldMemoryConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMemoryConfig(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, graph.FieldMemoryConfig, value)
		})
	}
	if _u.mutation.MemoryConfigCleared() {
		_spec.ClearField(graph.FieldMemoryConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(graph.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(graph.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   graph.NodesTable,
			Columns: []string{graph.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNodesIDs(); len(nodes) > 0 && !_u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   graph.NodesTable,
			Columns: []string{graph.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   graph.NodesTable,
			Columns: []string{graph.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   graph.ExecutionsTable,
			Columns: []string{graph.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(execution.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExecutionsIDs(); len(nodes) > 0 && !_u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   graph.ExecutionsTable,
			Columns: []string{graph.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(execution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   graph.ExecutionsTable,
			Columns: []string{graph.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(execution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{graph.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GraphUpdateOne is the builder for updating a single Graph entity.
type GraphUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GraphMutation
}

// SetName sets the "name" field.
func (_u *GraphUpdateOne) SetName(v string) *GraphUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GraphUpdateOne) SetNillableName(v *string) *GraphUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *GraphUpdateOne) SetVersion(v string) *GraphUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *GraphUpdateOne) SetNillableVersion(v *string) *GraphUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GraphUpdateOne) SetDescription(v string) *GraphUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GraphUpdateOne) SetNillableDescription(v *string) *GraphUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GraphUpdateOne) ClearDescription() *GraphUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetEntryNode sets the "entry_node" field.
func (_u *GraphUpdateOne) SetEntryNode(v string) *GraphUpdateOne {
	_u.mutation.SetEntryNode(v)
	return _u
}

// SetNillableEntryNode sets the "entry_node" field if the given value is not nil.
func (_u *GraphUpdateOne) SetNillableEntryNode(v *string) *GraphUpdateOne {
	if v != nil {
		_u.SetEntryNode(*v)
	}
	return _u
}

// SetDefinition sets the "definition" field.
func (_u *GraphUpdateOne) SetDefinition(v json.RawMessage) *GraphUpdateOne {
	_u.mutation.SetDefinition(v)
	return _u
}

// AppendDefinition appends value to the "definition" field.
func (_u *GraphUpdateOne) AppendDefinition(v json.RawMessage) *GraphUpdateOne {
	_u.mutation.AppendDefinition(v)
	return _u
}

// SetMemoryConfig sets the "memory_config" field.
func (_u *GraphUpdateOne) SetMemoryConfig(v json.RawMessage) *GraphUpdateOne {
	_u.mutation.SetMemoryConfig(v)
	return _u
}

// AppendMemoryConfig appends value to the "memory_config" field.
func (_u *GraphUpdateOne) AppendMemoryConfig(v json.RawMessage) *GraphUpdateOne {
	_u.mutation.AppendMemoryConfig(v)
	return _u
}

// ClearMemoryConfig clears the value of the "memory_config" field.
func (_u *GraphUpdateOne) ClearMemoryConfig() *GraphUpdateOne {
	_u.mutation.ClearMemoryConfig()
	return _u
}

// SetStatus sets the "status" field.
func (_u *GraphUpdateOne) SetStatus(v graph.Status) *GraphUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GraphUpdateOne) SetNillableStatus(v *graph.Status) *GraphUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GraphUpdateOne) SetUpdatedAt(v time.Time) *GraphUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddNodeIDs adds the "nodes" edge to the Node entity by IDs.
func (_u *GraphUpdateOne) AddNodeIDs(ids ...uuid.UUID) *GraphUpdateOne {
	_u.mutation.AddNodeIDs(ids...)
	return _u
}

// AddNodes adds the "nodes" edges to the Node entity.
func (_u *GraphUpdateOne) AddNodes(v ...*Node) *GraphUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNodeIDs(ids...)
}

// AddExecutionIDs adds the "executions" edge to the Execution entity by IDs.
func (_u *GraphUpdateOne) AddExecutionIDs(ids ...uuid.UUID) *GraphUpdateOne {
	_u.mutation.AddExecutionIDs(ids...)
	return _u
}

// AddExecutions adds the "executions" edges to the Execution entity.
func (_u *GraphUpdateOne) AddExecutions(v ...*Execution) *GraphUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExecutionIDs(ids...)
}

// Mutation returns the GraphMutation object of the builder.
func (_u *GraphUpdateOne) Mutation() *GraphMutation {
	return _u.mutation
}

// ClearNodes clears all "nodes" edges to the Node entity.
func (_u *GraphUpdateOne) ClearNodes() *GraphUpdateOne {
	_u.mutation.ClearNodes()
	return _u
}

// RemoveNodeIDs removes the "nodes" edge to Node entities by IDs.
func (_u *GraphUpdateOne) RemoveNodeIDs(ids ...uuid.UUID) *GraphUpdateOne {
	_u.mutation.RemoveNodeIDs(ids...)
	return _u
}

// RemoveNodes removes "nodes" edges to Node entities.
func (_u *GraphUpdateOne) RemoveNodes(v ...*Node) *GraphUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNodeIDs(ids...)
}

// ClearExecutions clears all "executions" edges to the Execution entity.
func (_u *GraphUpdateOne) ClearExecutions() *GraphUpdateOne {
	_u.mutation.ClearExecutions()
	return _u
}

// RemoveExecutionIDs removes the "executions" edge to Execution entities by IDs.
func (_u *GraphUpdateOne) RemoveExecutionIDs(ids ...uuid.UUID) *GraphUpdateOne {
	_u.mutation.RemoveExecutionIDs(ids...)
	return _u
}

// RemoveExecutions removes "executions" edges to Execution entities.
func (_u *GraphUpdateOne) RemoveExecutions(v ...*Execution) *GraphUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExecutionIDs(ids...)
}

// Where appends a list predicates to the GraphUpdate builder.
func (_u *GraphUpdateOne) Where(ps ...predicate.Graph) *GraphUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GraphUpdateOne) Select(field string, fields ...string) *GraphUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Graph entity.
func (_u *GraphUpdateOne) Save(ctx context.Context) (*Graph, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GraphUpdateOne) SaveX(ctx context.Context) *Graph {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GraphUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GraphUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GraphUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := graph.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GraphUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := graph.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Graph.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := graph.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Graph.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntryNode(); ok {
		if err := graph.EntryNodeValidator(v); err != nil {
			return &ValidationError{Name: "entry_node", err: fmt.Errorf(`ent: validator failed for field "Graph.entry_node": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := graph.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Graph.status": %w`, err)}
		}
	}
	return nil
}

func (_u *GraphUpdateOne) sqlSave(ctx context.Context) (_node *Graph, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(graph.Table, graph.Columns, sqlgraph.NewFieldSpec(graph.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Graph.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, graph.FieldID)
		for _, f := range fields {
			if !graph.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != graph.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(graph.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(graph.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(graph.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(graph.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.EntryNode(); ok {
		_spec.SetField(graph.FieldEntryNode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Definition(); ok {
		_spec.SetField(graph.FieldDefinition, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDefinition(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, graph.FieldDefinition, value)
		})
	}
	if value, ok := _u.mutation.MemoryConfig(); ok {
		_spec.SetField(graph.FieldMemoryConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMemoryConfig(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, graph.FieldMemoryConfig, value)
		})
	}
	if _u.mutation.MemoryConfigCleared() {
		_spec.ClearField(graph.FieldMemoryConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(graph.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(graph.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   graph.NodesTable,
			Columns: []string{graph.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNodesIDs(); len(nodes) > 0 && !_u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   graph.NodesTable,
			Columns: []string{graph.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   graph.NodesTable,
			Columns: []string{graph.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   graph.ExecutionsTable,
			Columns: []string{graph.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(execution.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExecutionsIDs(); len(nodes) > 0 && !_u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   graph.ExecutionsTable,
			Columns: []string{graph.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(execution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   graph.ExecutionsTable,
			Columns: []string{graph.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(execution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Graph{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{graph.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
