// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/aescanero/dago/ent/graph"
	"github.com/aescanero/dago/ent/node"
	"github.com/aescanero/dago/ent/predicate"
	"github.com/google/uuid"
)

// NodeUpdate is the builder for updating Node entities.
type NodeUpdate struct {
	config
	hooks    []Hook
	mutation *NodeMutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdate) Where(ps ...predicate.Node) *NodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNodeKey sets the "node_key" field.
func (_u *NodeUpdate) SetNodeKey(v string) *NodeUpdate {
	_u.mutation.SetNodeKey(v)
	return _u
}

// SetNillableNodeKey sets the "node_key" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableNodeKey(v *string) *NodeUpdate {
	if v != nil {
		_u.SetNodeKey(*v)
	}
	return _u
}

// SetPattern sets the "pattern" field.
func (_u *NodeUpdate) SetPattern(v node.Pattern) *NodeUpdate {
	_u.mutation.SetPattern(v)
	return _u
}

// SetNillablePattern sets the "pattern" field if the given value is not nil.
func (_u *NodeUpdate) SetNillablePattern(v *node.Pattern) *NodeUpdate {
	if v != nil {
		_u.SetPattern(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *NodeUpdate) SetConfig(v json.RawMessage) *NodeUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// AppendConfig appends value to the "config" field.
func (_u *NodeUpdate) AppendConfig(v json.RawMessage) *NodeUpdate {
	_u.mutation.AppendConfig(v)
	return _u
}

// SetPosition sets the "position" field.
func (_u *NodeUpdate) SetPosition(v json.RawMessage) *NodeUpdate {
	_u.mutation.SetPosition(v)
	return _u
}

// AppendPosition appends value to the "position" field.
func (_u *NodeUpdate) AppendPosition(v json.RawMessage) *NodeUpdate {
	_u.mutation.AppendPosition(v)
	return _u
}

// ClearPosition clears the value of the "position" field.
func (_u *NodeUpdate) ClearPosition() *NodeUpdate {
	_u.mutation.ClearPosition()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeUpdate) SetUpdatedAt(v time.Time) *NodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGraphID sets the "graph" edge to the Graph entity by ID.
func (_u *NodeUpdate) SetGraphID(id uuid.UUID) *NodeUpdate {
	_u.mutation.SetGraphID(id)
	return _u
}

// SetGraph sets the "graph" edge to the Graph entity.
func (_u *NodeUpdate) SetGraph(v *Graph) *NodeUpdate {
	return _u.SetGraphID(v.ID)
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdate) Mutation() *NodeMutation {
	return _u.mutation
}

// ClearGraph clears the "graph" edge to the Graph entity.
func (_u *NodeUpdate) ClearGraph() *NodeUpdate {
	_u.mutation.ClearGraph()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdate) check() error {
	if v, ok := _u.mutation.NodeKey(); ok {
		if err := node.NodeKeyValidator(v); err != nil {
			return &ValidationError{Name: "node_key", err: fmt.Errorf(`ent: validator failed for field "Node.node_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pattern(); ok {
		if err := node.PatternValidator(v); err != nil {
			return &ValidationError{Name: "pattern", err: fmt.Errorf(`ent: validator failed for field "Node.pattern": %w`, err)}
		}
	}
	if _u.mutation.GraphCleared() && len(_u.mutation.GraphIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Node.graph"`)
	}
	return nil
}

func (_u *NodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NodeKey(); ok {
		_spec.SetField(node.FieldNodeKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pattern(); ok {
		_spec.SetField(node.FieldPattern, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(node.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConfig(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldConfig, value)
		})
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(node.FieldPosition, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPosition(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldPosition, value)
		})
	}
	if _u.mutation.PositionCleared() {
		_spec.ClearField(node.FieldPosition, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GraphCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.GraphTable,
			Columns: []string{node.GraphColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(graph.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GraphIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.GraphTable,
			Columns: []string{node.GraphColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(graph.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeUpdateOne is the builder for updating a single Node entity.
type NodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeMutation
}

// SetNodeKey sets the "node_key" field.
func (_u *NodeUpdateOne) SetNodeKey(v string) *NodeUpdateOne {
	_u.mutation.SetNodeKey(v)
	return _u
}

// SetNillableNodeKey sets the "node_key" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableNodeKey(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetNodeKey(*v)
	}
	return _u
}

// SetPattern sets the "pattern" field.
func (_u *NodeUpdateOne) SetPattern(v node.Pattern) *NodeUpdateOne {
	_u.mutation.SetPattern(v)
	return _u
}

// SetNillablePattern sets the "pattern" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillablePattern(v *node.Pattern) *NodeUpdateOne {
	if v != nil {
		_u.SetPattern(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *NodeUpdateOne) SetConfig(v json.RawMessage) *NodeUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// AppendConfig appends value to the "config" field.
func (_u *NodeUpdateOne) AppendConfig(v json.RawMessage) *NodeUpdateOne {
	_u.mutation.AppendConfig(v)
	return _u
}

// SetPosition sets the "position" field.
func (_u *NodeUpdateOne) SetPosition(v json.RawMessage) *NodeUpdateOne {
	_u.mutation.SetPosition(v)
	return _u
}

// AppendPosition appends value to the "position" field.
func (_u *NodeUpdateOne) AppendPosition(v json.RawMessage) *NodeUpdateOne {
	_u.mutation.AppendPosition(v)
	return _u
}

// ClearPosition clears the value of the "position" field.
func (_u *NodeUpdateOne) ClearPosition() *NodeUpdateOne {
	_u.mutation.ClearPosition()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeUpdateOne) SetUpdatedAt(v time.Time) *NodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGraphID sets the "graph" edge to the Graph entity by ID.
func (_u *NodeUpdateOne) SetGraphID(id uuid.UUID) *NodeUpdateOne {
	_u.mutation.SetGraphID(id)
	return _u
}

// SetGraph sets the "graph" edge to the Graph entity.
func (_u *NodeUpdateOne) SetGraph(v *Graph) *NodeUpdateOne {
	return _u.SetGraphID(v.ID)
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdateOne) Mutation() *NodeMutation {
	return _u.mutation
}

// ClearGraph clears the "graph" edge to the Graph entity.
func (_u *NodeUpdateOne) ClearGraph() *NodeUpdateOne {
	_u.mutation.ClearGraph()
	return _u
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdateOne) Where(ps ...predicate.Node) *NodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeUpdateOne) Select(field string, fields ...string) *NodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Node entity.
func (_u *NodeUpdateOne) Save(ctx context.Context) (*Node, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdateOne) SaveX(ctx context.Context) *Node {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdateOne) check() error {
	if v, ok := _u.mutation.NodeKey(); ok {
		if err := node.NodeKeyValidator(v); err != nil {
			return &ValidationError{Name: "node_key", err: fmt.Errorf(`ent: validator failed for field "Node.node_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pattern(); ok {
		if err := node.PatternValidator(v); err != nil {
			return &ValidationError{Name: "pattern", err: fmt.Errorf(`ent: validator failed for field "Node.pattern": %w`, err)}
		}
	}
	if _u.mutation.GraphCleared() && len(_u.mutation.GraphIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Node.graph"`)
	}
	return nil
}

func (_u *NodeUpdateOne) sqlSave(ctx context.Context) (_node *Node, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Node.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for _, f := range fields {
			if !node.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NodeKey(); ok {
		_spec.SetField(node.FieldNodeKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pattern(); ok {
		_spec.SetField(node.FieldPattern, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(node.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConfig(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldConfig, value)
		})
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(node.FieldPosition, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPosition(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldPosition, value)
		})
	}
	if _u.mutation.PositionCleared() {
		_spec.ClearField(node.FieldPosition, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GraphCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.GraphTable,
			Columns: []string{node.GraphColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(graph.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GraphIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.GraphTable,
			Columns: []string{node.GraphColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(graph.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Node{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
