// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/aescanero/dago/ent/orgunit"
	"github.com/aescanero/dago/ent/predicate"
	"github.com/aescanero/dago/ent/user"
	"github.com/google/uuid"
)

// OrgUnitUpdate is the builder for updating OrgUnit entities.
type OrgUnitUpdate struct {
	config
	hooks    []Hook
	mutation *OrgUnitMutation
}

// Where appends a list predicates to the OrgUnitUpdate builder.
func (_u *OrgUnitUpdate) Where(ps ...predicate.OrgUnit) *OrgUnitUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *OrgUnitUpdate) SetName(v string) *OrgUnitUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OrgUnitUpdate) SetNillableName(v *string) *OrgUnitUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *OrgUnitUpdate) SetPath(v string) *OrgUnitUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *OrgUnitUpdate) SetNillablePath(v *string) *OrgUnitUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *OrgUnitUpdate) SetTags(v []string) *OrgUnitUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *OrgUnitUpdate) AppendTags(v []string) *OrgUnitUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrgUnitUpdate) SetUpdatedAt(v time.Time) *OrgUnitUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetParentID sets the "parent" edge to the OrgUnit entity by ID.
func (_u *OrgUnitUpdate) SetParentID(id uuid.UUID) *OrgUnitUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the OrgUnit entity by ID if the given value is not nil.
func (_u *OrgUnitUpdate) SetNillableParentID(id *uuid.UUID) *OrgUnitUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the OrgUnit entity.
func (_u *OrgUnitUpdate) SetParent(v *OrgUnit) *OrgUnitUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the OrgUnit entity by IDs.
func (_u *OrgUnitUpdate) AddChildIDs(ids ...uuid.UUID) *OrgUnitUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the OrgUnit entity.
func (_u *OrgUnitUpdate) AddChildren(v ...*OrgUnit) *OrgUnitUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *OrgUnitUpdate) AddUserIDs(ids ...uuid.UUID) *OrgUnitUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *OrgUnitUpdate) AddUsers(v ...*User) *OrgUnitUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the OrgUnitMutation object of the builder.
func (_u *OrgUnitUpdate) Mutation() *OrgUnitMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the OrgUnit entity.
func (_u *OrgUnitUpdate) ClearParent() *OrgUnitUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the OrgUnit entity.
func (_u *OrgUnitUpdate) ClearChildren() *OrgUnitUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to OrgUnit entities by IDs.
func (_u *OrgUnitUpdate) RemoveChildIDs(ids ...uuid.UUID) *OrgUnitUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to OrgUnit entities.
func (_u *OrgUnitUpdate) RemoveChildren(v ...*OrgUnit) *OrgUnitUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *OrgUnitUpdate) ClearUsers() *OrgUnitUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *OrgUnitUpdate) RemoveUserIDs(ids ...uuid.UUID) *OrgUnitUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *OrgUnitUpdate) RemoveUsers(v ...*User) *OrgUnitUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrgUnitUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrgUnitUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrgUnitUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrgUnitUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrgUnitUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := orgunit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrgUnitUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := orgunit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OrgUnit.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := orgunit.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "OrgUnit.path": %w`, err)}
		}
	}
	return nil
}

func (_u *OrgUnitUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orgunit.Table, orgunit.Columns, sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(orgunit.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(orgunit.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(orgunit.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, orgunit.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(orgunit.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgunit.ParentTable,
			Columns: []string{orgunit.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgunit.ParentTable,
			Columns: []string{orgunit.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.ChildrenTable,
			Columns: []string{orgunit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.ChildrenTable,
			Columns: []string{orgunit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.ChildrenTable,
			Columns: []string{orgunit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.UsersTable,
			Columns: []string{orgunit.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.UsersTable,
			Columns: []string{orgunit.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.UsersTable,
			Columns: []string{orgunit.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orgunit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrgUnitUpdateOne is the builder for updating a single OrgUnit entity.
type OrgUnitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrgUnitMutation
}

// SetName sets the "name" field.
func (_u *OrgUnitUpdateOne) SetName(v string) *OrgUnitUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OrgUnitUpdateOne) SetNillableName(v *string) *OrgUnitUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *OrgUnitUpdateOne) SetPath(v string) *OrgUnitUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *OrgUnitUpdateOne) SetNillablePath(v *string) *OrgUnitUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *OrgUnitUpdateOne) SetTags(v []string) *OrgUnitUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *OrgUnitUpdateOne) AppendTags(v []string) *OrgUnitUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrgUnitUpdateOne) SetUpdatedAt(v time.Time) *OrgUnitUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetParentID sets the "parent" edge to the OrgUnit entity by ID.
func (_u *OrgUnitUpdateOne) SetParentID(id uuid.UUID) *OrgUnitUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the OrgUnit entity by ID if the given value is not nil.
func (_u *OrgUnitUpdateOne) SetNillableParentID(id *uuid.UUID) *OrgUnitUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the OrgUnit entity.
func (_u *OrgUnitUpdateOne) SetParent(v *OrgUnit) *OrgUnitUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the OrgUnit entity by IDs.
func (_u *OrgUnitUpdateOne) AddChildIDs(ids ...uuid.UUID) *OrgUnitUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the OrgUnit entity.
func (_u *OrgUnitUpdateOne) AddChildren(v ...*OrgUnit) *OrgUnitUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *OrgUnitUpdateOne) AddUserIDs(ids ...uuid.UUID) *OrgUnitUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *OrgUnitUpdateOne) AddUsers(v ...*User) *OrgUnitUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the OrgUnitMutation object of the builder.
func (_u *OrgUnitUpdateOne) Mutation() *OrgUnitMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the OrgUnit entity.
func (_u *OrgUnitUpdateOne) ClearParent() *OrgUnitUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the OrgUnit entity.
func (_u *OrgUnitUpdateOne) ClearChildren() *OrgUnitUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to OrgUnit entities by IDs.
func (_u *OrgUnitUpdateOne) RemoveChildIDs(ids ...uuid.UUID) *OrgUnitUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to OrgUnit entities.
func (_u *OrgUnitUpdateOne) RemoveChildren(v ...*OrgUnit) *OrgUnitUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *OrgUnitUpdateOne) ClearUsers() *OrgUnitUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *OrgUnitUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *OrgUnitUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *OrgUnitUpdateOne) RemoveUsers(v ...*User) *OrgUnitUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the OrgUnitUpdate builder.
func (_u *OrgUnitUpdateOne) Where(ps ...predicate.OrgUnit) *OrgUnitUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrgUnitUpdateOne) Select(field string, fields ...string) *OrgUnitUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrgUnit entity.
func (_u *OrgUnitUpdateOne) Save(ctx context.Context) (*OrgUnit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrgUnitUpdateOne) SaveX(ctx context.Context) *OrgUnit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrgUnitUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrgUnitUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrgUnitUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := orgunit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrgUnitUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := orgunit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OrgUnit.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := orgunit.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "OrgUnit.path": %w`, err)}
		}
	}
	return nil
}

func (_u *OrgUnitUpdateOne) sqlSave(ctx context.Context) (_node *OrgUnit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orgunit.Table, orgunit.Columns, sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrgUnit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orgunit.FieldID)
		for _, f := range fields {
			if !orgunit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orgunit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(orgunit.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(orgunit.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(orgunit.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, orgunit.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(orgunit.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgunit.ParentTable,
			Columns: []string{orgunit.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgunit.ParentTable,
			Columns: []string{orgunit.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.ChildrenTable,
			Columns: []string{orgunit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.ChildrenTable,
			Columns: []string{orgunit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.ChildrenTable,
			Columns: []string{orgunit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.UsersTable,
			Columns: []string{orgunit.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.UsersTable,
			Columns: []string{orgunit.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.UsersTable,
			Columns: []string{orgunit.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrgUnit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orgunit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
