// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aescanero/dago/ent/orgunit"
	"github.com/aescanero/dago/ent/user"
	"github.com/google/uuid"
)

// OrgUnitCreate is the builder for creating a OrgUnit entity.
type OrgUnitCreate struct {
	config
	mutation *OrgUnitMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *OrgUnitCreate) SetName(v string) *OrgUnitCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *OrgUnitCreate) SetPath(v string) *OrgUnitCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *OrgUnitCreate) SetTags(v []string) *OrgUnitCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrgUnitCreate) SetCreatedAt(v time.Time) *OrgUnitCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableCreatedAt(v *time.Time) *OrgUnitCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrgUnitCreate) SetUpdatedAt(v time.Time) *OrgUnitCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableUpdatedAt(v *time.Time) *OrgUnitCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OrgUnitCreate) SetID(v uuid.UUID) *OrgUnitCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableID(v *uuid.UUID) *OrgUnitCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetParentID sets the "parent" edge to the OrgUnit entity by ID.
func (_c *OrgUnitCreate) SetParentID(id uuid.UUID) *OrgUnitCreate {
	_c.mutation.SetParentID(id)
	return _c
}

// SetNillableParentID sets the "parent" edge to the OrgUnit entity by ID if the given value is not nil.
func (_c *OrgUnitCreate) SetNillableParentID(id *uuid.UUID) *OrgUnitCreate {
	if id != nil {
		_c = _c.SetParentID(*id)
	}
	return _c
}

// SetParent sets the "parent" edge to the OrgUnit entity.
func (_c *OrgUnitCreate) SetParent(v *OrgUnit) *OrgUnitCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the OrgUnit entity by IDs.
func (_c *OrgUnitCreate) AddChildIDs(ids ...uuid.UUID) *OrgUnitCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the OrgUnit entity.
func (_c *OrgUnitCreate) AddChildren(v ...*OrgUnit) *OrgUnitCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_c *OrgUnitCreate) AddUserIDs(ids ...uuid.UUID) *OrgUnitCreate {
	_c.mutation.AddUserIDs(ids...)
	return _c
}

// AddUsers adds the "users" edges to the User entity.
func (_c *OrgUnitCreate) AddUsers(v ...*User) *OrgUnitCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserIDs(ids...)
}

// Mutation returns the OrgUnitMutation object of the builder.
func (_c *OrgUnitCreate) Mutation() *OrgUnitMutation {
	return _c.mutation
}

// Save creates the OrgUnit in the database.
func (_c *OrgUnitCreate) Save(ctx context.Context) (*OrgUnit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrgUnitCreate) SaveX(ctx context.Context) *OrgUnit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgUnitCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgUnitCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrgUnitCreate) defaults() {
	if _, ok := _c.mutation.Tags(); !ok {
		v := orgunit.DefaultTags
		_c.mutation.SetTags(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := orgunit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := orgunit.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := orgunit.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrgUnitCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OrgUnit.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := orgunit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OrgUnit.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "OrgUnit.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := orgunit.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "OrgUnit.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "OrgUnit.tags"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrgUnit.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OrgUnit.updated_at"`)}
	}
	return nil
}

func (_c *OrgUnitCreate) sqlSave(ctx context.Context) (*OrgUnit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrgUnitCreate) createSpec() (*OrgUnit, *sqlgraph.CreateSpec) {
	var (
		_node = &OrgUnit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(orgunit.Table, sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(orgunit.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(orgunit.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(orgunit.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(orgunit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(orgunit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgunit.ParentTable,
			Columns: []string{orgunit.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.org_unit_children = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.ChildrenTable,
			Columns: []string{orgunit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgunit.UsersTable,
			Columns: []string{orgunit.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrgUnitCreateBulk is the builder for creating many OrgUnit entities in bulk.
type OrgUnitCreateBulk struct {
	config
	err      error
	builders []*OrgUnitCreate
}

// Save creates the OrgUnit entities in the database.
func (_c *OrgUnitCreateBulk) Save(ctx context.Context) ([]*OrgUnit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrgUnit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrgUnitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrgUnitCreateBulk) SaveX(ctx context.Context) []*OrgUnit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgUnitCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgUnitCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
