// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"time"

	"github.com/aescanero/dago/ent/execution"
	"github.com/aescanero/dago/ent/graph"
	"github.com/aescanero/dago/ent/node"
	"github.com/aescanero/dago/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	executionFields := schema.Execution{}.Fields()
	_ = executionFields
	// executionDescCurrentNode is the schema descriptor for current_node field.
	executionDescCurrentNode := executionFields[2].Descriptor()
	// execution.CurrentNodeValidator is a validator for the "current_node" field. It is called by the builders before save.
	execution.CurrentNodeValidator = executionDescCurrentNode.Validators[0].(func(string) error)
	// executionDescVariables is the schema descriptor for variables field.
	executionDescVariables := executionFields[3].Descriptor()
	// execution.DefaultVariables holds the default value on creation for the variables field.
	execution.DefaultVariables = executionDescVariables.Default.(json.RawMessage)
	// executionDescMessages is the schema descriptor for messages field.
	executionDescMessages := executionFields[4].Descriptor()
	// execution.DefaultMessages holds the default value on creation for the messages field.
	execution.DefaultMessages = executionDescMessages.Default.(json.RawMessage)
	// executionDescNodeResults is the schema descriptor for node_results field.
	executionDescNodeResults := executionFields[5].Descriptor()
	// execution.DefaultNodeResults holds the default value on creation for the node_results field.
	execution.DefaultNodeResults = executionDescNodeResults.Default.(json.RawMessage)
	// executionDescCreatedAt is the schema descriptor for created_at field.
	executionDescCreatedAt := executionFields[9].Descriptor()
	// execution.DefaultCreatedAt holds the default value on creation for the created_at field.
	execution.DefaultCreatedAt = executionDescCreatedAt.Default.(func() time.Time)
	// executionDescUpdatedAt is the schema descriptor for updated_at field.
	executionDescUpdatedAt := executionFields[10].Descriptor()
	// execution.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	execution.DefaultUpdatedAt = executionDescUpdatedAt.Default.(func() time.Time)
	// execution.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	execution.UpdateDefaultUpdatedAt = executionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// executionDescID is the schema descriptor for id field.
	executionDescID := executionFields[0].Descriptor()
	// execution.DefaultID holds the default value on creation for the id field.
	execution.DefaultID = executionDescID.Default.(func() uuid.UUID)
	graphFields := schema.Graph{}.Fields()
	_ = graphFields
	// graphDescName is the schema descriptor for name field.
	graphDescName := graphFields[1].Descriptor()
	// graph.NameValidator is a validator for the "name" field. It is called by the builders before save.
	graph.NameValidator = func() func(string) error {
		validators := graphDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// graphDescVersion is the schema descriptor for version field.
	graphDescVersion := graphFields[2].Descriptor()
	// graph.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	graph.VersionValidator = func() func(string) error {
		validators := graphDescVersion.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(version string) error {
			for _, fn := range fns {
				if err := fn(version); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// graphDescEntryNode is the schema descriptor for entry_node field.
	graphDescEntryNode := graphFields[4].Descriptor()
	// graph.EntryNodeValidator is a validator for the "entry_node" field. It is called by the builders before save.
	graph.EntryNodeValidator = func() func(string) error {
		validators := graphDescEntryNode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(entry_node string) error {
			for _, fn := range fns {
				if err := fn(entry_node); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// graphDescCreatedAt is the schema descriptor for created_at field.
	graphDescCreatedAt := graphFields[8].Descriptor()
	// graph.DefaultCreatedAt holds the default value on creation for the created_at field.
	graph.DefaultCreatedAt = graphDescCreatedAt.Default.(func() time.Time)
	// graphDescUpdatedAt is the schema descriptor for updated_at field.
	graphDescUpdatedAt := graphFields[9].Descriptor()
	// graph.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	graph.DefaultUpdatedAt = graphDescUpdatedAt.Default.(func() time.Time)
	// graph.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	graph.UpdateDefaultUpdatedAt = graphDescUpdatedAt.UpdateDefault.(func() time.Time)
	// graphDescID is the schema descriptor for id field.
	graphDescID := graphFields[0].Descriptor()
	// graph.DefaultID holds the default value on creation for the id field.
	graph.DefaultID = graphDescID.Default.(func() uuid.UUID)
	nodeFields := schema.Node{}.Fields()
	_ = nodeFields
	// nodeDescNodeKey is the schema descriptor for node_key field.
	nodeDescNodeKey := nodeFields[1].Descriptor()
	// node.NodeKeyValidator is a validator for the "node_key" field. It is called by the builders before save.
	node.NodeKeyValidator = func() func(string) error {
		validators := nodeDescNodeKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(node_key string) error {
			for _, fn := range fns {
				if err := fn(node_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// nodeDescCreatedAt is the schema descriptor for created_at field.
	nodeDescCreatedAt := nodeFields[5].Descriptor()
	// node.DefaultCreatedAt holds the default value on creation for the created_at field.
	node.DefaultCreatedAt = nodeDescCreatedAt.Default.(func() time.Time)
	// nodeDescUpdatedAt is the schema descriptor for updated_at field.
	nodeDescUpdatedAt := nodeFields[6].Descriptor()
	// node.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	node.DefaultUpdatedAt = nodeDescUpdatedAt.Default.(func() time.Time)
	// node.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	node.UpdateDefaultUpdatedAt = nodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// nodeDescID is the schema descriptor for id field.
	nodeDescID := nodeFields[0].Descriptor()
	// node.DefaultID holds the default value on creation for the id field.
	node.DefaultID = nodeDescID.Default.(func() uuid.UUID)
}
