// Code generated by ent, DO NOT EDIT.

package graph

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/aescanero/dago/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Graph {
	return predicate.Graph(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Graph {
	return predicate.Graph(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Graph {
	return predicate.Graph(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Graph {
	return predicate.Graph(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Graph {
	return predicate.Graph(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Graph {
	return predicate.Graph(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Graph {
	return predicate.Graph(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldName, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldVersion, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldDescription, v))
}

// EntryNode applies equality check predicate on the "entry_node" field. It's identical to EntryNodeEQ.
func EntryNode(v string) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldEntryNode, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Graph {
	return predicate.Graph(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Graph {
	return predicate.Graph(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Graph {
	return predicate.Graph(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Graph {
	return predicate.Graph(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Graph {
	return predicate.Graph(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Graph {
	return predicate.Graph(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Graph {
	return predicate.Graph(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Graph {
	return predicate.Graph(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Graph {
	return predicate.Graph(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Graph {
	return predicate.Graph(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Graph {
	return predicate.Graph(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Graph {
	return predicate.Graph(sql.FieldContainsFold(FieldName, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.Graph {
	return predicate.Graph(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.Graph {
	return predicate.Graph(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.Graph {
	return predicate.Graph(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.Graph {
	return predicate.Graph(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.Graph {
	return predicate.Graph(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.Graph {
	return predicate.Graph(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.Graph {
	return predicate.Graph(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.Graph {
	return predicate.Graph(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.Graph {
	return predicate.Graph(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.Graph {
	return predicate.Graph(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.Graph {
	return predicate.Graph(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.Graph {
	return predicate.Graph(sql.FieldContainsFold(FieldVersion, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Graph {
	return predicate.Graph(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Graph {
	return predicate.Graph(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Graph {
	return predicate.Graph(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Graph {
	return predicate.Graph(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Graph {
	return predicate.Graph(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Graph {
	return predicate.Graph(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Graph {
	return predicate.Graph(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Graph {
	return predicate.Graph(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Graph {
	return predicate.Graph(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Graph {
	return predicate.Graph(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Graph {
	return predicate.Graph(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Graph {
	return predicate.Graph(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Graph {
	return predicate.Graph(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Graph {
	return predicate.Graph(sql.FieldContainsFold(FieldDescription, v))
}

// EntryNodeEQ applies the EQ predicate on the "entry_node" field.
func EntryNodeEQ(v string) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldEntryNode, v))
}

// EntryNodeNEQ applies the NEQ predicate on the "entry_node" field.
func EntryNodeNEQ(v string) predicate.Graph {
	return predicate.Graph(sql.FieldNEQ(FieldEntryNode, v))
}

// EntryNodeIn applies the In predicate on the "entry_node" field.
func EntryNodeIn(vs ...string) predicate.Graph {
	return predicate.Graph(sql.FieldIn(FieldEntryNode, vs...))
}

// EntryNodeNotIn applies the NotIn predicate on the "entry_node" field.
func EntryNodeNotIn(vs ...string) predicate.Graph {
	return predicate.Graph(sql.FieldNotIn(FieldEntryNode, vs...))
}

// EntryNodeGT applies the GT predicate on the "entry_node" field.
func EntryNodeGT(v string) predicate.Graph {
	return predicate.Graph(sql.FieldGT(FieldEntryNode, v))
}

// EntryNodeGTE applies the GTE predicate on the "entry_node" field.
func EntryNodeGTE(v string) predicate.Graph {
	return predicate.Graph(sql.FieldGTE(FieldEntryNode, v))
}

// EntryNodeLT applies the LT predicate on the "entry_node" field.
func EntryNodeLT(v string) predicate.Graph {
	return predicate.Graph(sql.FieldLT(FieldEntryNode, v))
}

// EntryNodeLTE applies the LTE predicate on the "entry_node" field.
func EntryNodeLTE(v string) predicate.Graph {
	return predicate.Graph(sql.FieldLTE(FieldEntryNode, v))
}

// EntryNodeContains applies the Contains predicate on the "entry_node" field.
func EntryNodeContains(v string) predicate.Graph {
	return predicate.Graph(sql.FieldContains(FieldEntryNode, v))
}

// EntryNodeHasPrefix applies the HasPrefix predicate on the "entry_node" field.
func EntryNodeHasPrefix(v string) predicate.Graph {
	return predicate.Graph(sql.FieldHasPrefix(FieldEntryNode, v))
}

// EntryNodeHasSuffix applies the HasSuffix predicate on the "entry_node" field.
func EntryNodeHasSuffix(v string) predicate.Graph {
	return predicate.Graph(sql.FieldHasSuffix(FieldEntryNode, v))
}

// EntryNodeEqualFold applies the EqualFold predicate on the "entry_node" field.
func EntryNodeEqualFold(v string) predicate.Graph {
	return predicate.Graph(sql.FieldEqualFold(FieldEntryNode, v))
}

// EntryNodeContainsFold applies the ContainsFold predicate on the "entry_node" field.
func EntryNodeContainsFold(v string) predicate.Graph {
	return predicate.Graph(sql.FieldContainsFold(FieldEntryNode, v))
}

// MemoryConfigIsNil applies the IsNil predicate on the "memory_config" field.
func MemoryConfigIsNil() predicate.Graph {
	return predicate.Graph(sql.FieldIsNull(FieldMemoryConfig))
}

// MemoryConfigNotNil applies the NotNil predicate on the "memory_config" field.
func MemoryConfigNotNil() predicate.Graph {
	return predicate.Graph(sql.FieldNotNull(FieldMemoryConfig))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Graph {
	return predicate.Graph(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Graph {
	return predicate.Graph(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Graph {
	return predicate.Graph(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Graph {
	return predicate.Graph(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasNodes applies the HasEdge predicate on the "nodes" edge.
func HasNodes() predicate.Graph {
	return predicate.Graph(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NodesTable, NodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodesWith applies the HasEdge predicate on the "nodes" edge with a given conditions (other predicates).
func HasNodesWith(preds ...predicate.Node) predicate.Graph {
	return predicate.Graph(func(s *sql.Selector) {
		step := newNodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExecutions applies the HasEdge predicate on the "executions" edge.
func HasExecutions() predicate.Graph {
	return predicate.Graph(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExecutionsTable, ExecutionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExecutionsWith applies the HasEdge predicate on the "executions" edge with a given conditions (other predicates).
func HasExecutionsWith(preds ...predicate.Execution) predicate.Graph {
	return predicate.Graph(func(s *sql.Selector) {
		step := newExecutionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Graph) predicate.Graph {
	return predicate.Graph(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Graph) predicate.Graph {
	return predicate.Graph(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Graph) predicate.Graph {
	return predicate.Graph(sql.NotPredicates(p))
}
