// Generated by openapi-typescript — regenerate with: make gen-api-types
// Do not edit manually.

export type paths = {
  "/graphs": {
    get: {
      parameters: {
        query?: {
          page?: number;
          per_page?: number;
          status?: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["GraphListResponse"];
          };
        };
      };
    };
  };
};

export type components = {
  schemas: {
    GraphListResponse: {
      items: GraphResponse[];
      pagination: Pagination;
    };
    GraphResponse: {
      id: string;
      name: string;
      version: string;
      status: string;
      created_at: string;
      updated_at: string;
    };
    Pagination: {
      page: number;
      per_page: number;
      total: number;
      total_pages: number;
    };
    TokenResponse: {
      access_token: string;
      token_type: "Bearer";
      expires_in: number;
    };
  };
};

type GraphResponse = components["schemas"]["GraphResponse"];
type Pagination = components["schemas"]["Pagination"];
