// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Execution is the predicate function for execution builders.
type Execution func(*sql.Selector)

// Graph is the predicate function for graph builders.
type Graph func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// OrgUnit is the predicate function for orgunit builders.
type OrgUnit func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
